### PR TITLE
chore: re-raise exception after max attempts

### PR DESCRIPTION
**Pull request by jon-hagg**
### Purpose
Various retry improvements, mostly for wind data.
* add `raises` parameter to enable re-raising allowed exception
* suppress error if 500 response on last retry (wind data only)
* wrap processing of each response into `try/except` and treat errors as missing data

### Testing
Ran the notebook again, with mixed results, but 100% success on the last one.

### Time estimate
10 min

### CODE REVIEW

**Comment by rouille** [comment]
It looks good. That said one test fails for 3.8

**Comment by rouille** [comment]
I have run the notebook and I have got the following error:
```

data, missing = rap.retrieve_data(wind_farm, start_date='2021-01-18', end_date='2021-01-21')

 50%|█████     | 48/96 [02:51<01:14,  1.55s/it] 

Max retries reached!!

---------------------------------------------------------------------------
TransientError                            Traceback (most recent call last)
<ipython-input-5-a7466117ea0f> in <module>
----> 1 data, missing = rap.retrieve_data(wind_farm, start_date='2021-01-18', end_date='2021-01-21')

~/CEM/PreREISE/prereise/gather/winddata/rap/rap.py in retrieve_data(wind_farm, start_date, end_date)
     81     first = True
     82     request_iter = enumerate(noaa.get_hourly_data(start, end))
---> 83     for i, response in tqdm(request_iter, total=url_count):
     84 
     85         data_tmp = pd.DataFrame(

~/.local/share/virtualenvs/PreREISE-Yr21Ys7H/lib/python3.8/site-packages/tqdm/_tqdm.py in __iter__(self)
   1000 """, fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1001 
-> 1002             for obj in iterable:
   1003                 yield obj
   1004                 # Update and possibly print the progressbar.

~/CEM/PreREISE/prereise/gather/winddata/rap/noaa_api.py in get_hourly_data(self, start, end)
     99 
    100         for time_slice in self.iter_hours(start, end):
--> 101             response = download(time_slice)
    102             if response.status_code == 404:
    103                 print(f"Got 404 response, trying fallback url.")

~/CEM/PreREISE/prereise/gather/request_util.py in wrapper(*args, **kwargs)
     74                     if func.retry_count == retry_count:
     75                         print("Max retries reached!!")
---> 76                         raise e
     77 
     78         return wrapper

~/CEM/PreREISE/prereise/gather/request_util.py in wrapper(*args, **kwargs)
     70                 func.retry_count = i + 1
     71                 try:
---> 72                     return limiter.invoke(lambda: func(*args, **kwargs))
     73                 except allowed_exceptions as e:
     74                     if func.retry_count == retry_count:

~/CEM/PreREISE/prereise/gather/request_util.py in invoke(self, action)
     29         """
     30         if self.interval is None:
---> 31             return action()
     32         elapsed = time.time() - self.last_run_at
     33         if elapsed < self.interval:

~/CEM/PreREISE/prereise/gather/request_util.py in <lambda>()
     70                 func.retry_count = i + 1
     71                 try:
---> 72                     return limiter.invoke(lambda: func(*args, **kwargs))
     73                 except allowed_exceptions as e:
     74                     if func.retry_count == retry_count:

~/CEM/PreREISE/prereise/gather/winddata/rap/noaa_api.py in download(time_slice, fallback)
     95             if resp.status_code == 500:
     96                 msg = f"Server error for url={resp.url}, retry_count={download.retry_count}"
---> 97                 raise TransientError(msg)
     98             return resp
     99 

TransientError: Server error for url=https://www.ncei.noaa.gov/thredds/ncss/model-rap130/202101/20210120/rap_130_20210120_0000_000.grb2?var=u-component_of_wind_height_above_ground&var=v-component_of_wind_height_above_ground&disableProjSubset=on&horizStride=1&addLatLon=true&accept=netCDF&north=49.8203&south=25.3307&west=-122.855&east=-96.2967, retry_count=0
```
when I paste the url in my browser, the file can be downloaded

**Comment by rouille** [comment]
In fact, we should move to the next iteration after the max attempt is reached. It can happen that a file is actually missing here and there when we build a full year profile. That is why we developed some methods to impute incomplete time series.

**Comment by jon-hagg** [comment]
Added try/catch logic to the loop over responses in `rap.py` to deal with an error I was getting, `OSError` which said `netcdf: Invalid argument: b'tmp.nc'`. Curious if anyone knows that this means, and if it's reasonable to treat it as missing data. When I run the notebook, I got this on 10 out of 24 files, but the fraction varies.

**Review by rouille — APPROVED** [review]
Thanks

**Pull request merged**
