### PR TITLE
Update dependencies and python versions

### LINKED ISSUE #304: Remove obsolete import statements
Use `ModelImmutables` object instead to access the geographical mappings in:
* prereise/gather/demanddata/nrel_efs/tests/test_aggregate_demand.py:from powersimdata.network.usa_tamu.constants.zones import abv2state
* prereise/gather/demanddata/nrel_efs/tests/test_get_efs_data.py:from powersimdata.network.usa_tamu.constants.zones import abv2state
* prereise/gather/demanddata/nrel_efs/tests/test_map_states.py:from powersimdata.network.usa_tamu.constants.zones import abv2state, id2abv
* prereise/gather/demanddata/nrel_efs/map_states.py:from powersimdata.network.usa_tamu.constants.zones import (
* prereise/gather/demanddata/eia/demo/eastern_demand_v6_demo/miso/.ipynb_checkpoints/split_miso_into_subareas-checkpoint.ipynb:    "from powersimdata.network.usa_tamu.constants.zones import abv2state"
* prereise/gather/demanddata/eia/demo/eastern_demand_v6_demo/miso/split_miso_into_subareas.ipynb:    "from powersimdata.network.usa_tamu.constants.zones import abv2state"
* prereise/gather/winddata/rap/rap.py:from powersimdata.network.usa_tamu.constants.zones import id2abv
* prereise/gather/hydrodata/eia/demo/eastern_hydro_v3_demo/.ipynb_checkpoints/eastern_hydro_v3_demo-checkpoint.ipynb:    "from powersimdata.network.usa_tamu.constants.zones import (interconnect2loadzone, \n",
* prereise/gather/hydrodata/eia/demo/eastern_hydro_v3_demo/eastern_hydro_v3_demo.ipynb:    "from * powersimdata.network.usa_tamu.constants.zones import (interconnect2loadzone, \n",
* prereise/gather/hydrodata/eia/demo/.ipynb_checkpoints/western_hydro_v2_demo-checkpoint.ipynb:    "from * powersimdata.network.usa_tamu.constants.zones import loadzone2state, state2loadzone\n",
* prereise/gather/hydrodata/eia/decompose_profile.py:from powersimdata.network.usa_tamu.constants.zones import abv2interconnect, abv2loadzone
* prereise/gather/hydrodata/eia/net_demand.py:from powersimdata.network.usa_tamu.constants.zones import abv2loadzone

### PR DESCRIPTION
**Pull request by rouille**
[Pull Request doc](https://breakthrough-energy.github.io/docs/user/git_guide.html#d-pull-request)

### Purpose
Update version of `powersimdata` to **0.5.4** (latest). Closes #304.

### What the code is doing
After updating `powersimdata`, some tests were failing because geographical constants could not be accessed anymore. This has been fixed  using a `ModelImmutables` object.

### Testing
Existing unit tests

### Where to look
* **Pipfile**, **requirements.txt** and **setup.cfg** files have been updated and the **Pipfile.lock** has been regenerated.
* Refactor some modules to properly access geographical mappings
* Increase a title underline in the docs to supress a warning when running `sphinx`

### Usage Example/Visuals
N/A

### Time estimate
5min

### CODE REVIEW

**Review by lanesmith — APPROVED** [review]
Looks good to me!

**Review by BainanXia — APPROVED** [review]
Just wonder the dependency issues for 3.10

**Comment by rouille** [comment]
> Just wonder the dependency issues for 3.10

Below is the error:
```
[~/CEM/PreREISE] (ben/update) brdo$ pipenv lock --python 3.10.3
Creating a virtualenv for this project...
Pipfile: /Users/brdo/CEM/PreREISE/Pipfile
Using /Users/brdo/.pyenv/versions/3.10.3/bin/python3 (3.10.3) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.10.3.final.0-64 in 395ms
  creator CPython3Posix(dest=/Users/brdo/.local/share/virtualenvs/PreREISE-Yr21Ys7H, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/brdo/Library/Application Support/virtualenv)
    added seed packages: pip==22.2.2, setuptools==63.4.3, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/brdo/.local/share/virtualenvs/PreREISE-Yr21Ys7H
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 

CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement nrel-pysam~=2.2 (from versions: 1.2.1, 2.1.1, 3.0.0, 3.0.1)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 743, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 704, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 685, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1398, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1127, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 905, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for nrel-pysam~=2.2
```
We would need to update `nrel-pysam`. Version 3.0.0 supports python 3.10 according to the [release notes](https://pypi.org/project/NREL-PySAM/). I will try and update the PR if it works.

**Comment by rouille** [comment]
> > Just wonder the dependency issues for 3.10
> 
> Below is the error:
> 
> ```
> [~/CEM/PreREISE] (ben/update) brdo$ pipenv lock --python 3.10.3
> Creating a virtualenv for this project...
> Pipfile: /Users/brdo/CEM/PreREISE/Pipfile
> Using /Users/brdo/.pyenv/versions/3.10.3/bin/python3 (3.10.3) to create virtualenv...
> ⠦ Creating virtual environment...created virtual environment CPython3.10.3.final.0-64 in 395ms
>   creator CPython3Posix(dest=/Users/brdo/.local/share/virtualenvs/PreREISE-Yr21Ys7H, clear=False, no_vcs_ignore=False, global=False)
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/brdo/Library/Application Support/virtualenv)
>     added seed packages: pip==22.2.2, setuptools==63.4.3, wheel==0.37.1
>   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> 
> ✔ Successfully created virtual environment! 
> Virtualenv location: /Users/brdo/.local/share/virtualenvs/PreREISE-Yr21Ys7H
> Locking [dev-packages] dependencies...
> Building requirements...
> Resolving dependencies...
> ✔ Success! 
> Locking [packages] dependencies...
> Building requirements...
> Resolving dependencies...
> ✘ Locking Failed! 
> 
> CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement nrel-pysam~=2.2 (from versions: 1.2.1, 2.1.1, 3.0.0, 3.0.1)
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 743, in _main
> [ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 704, in resolve_packages
> [ResolutionFailure]:       results, resolver = resolve(
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 685, in resolve
> [ResolutionFailure]:       return resolve_deps(
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1398, in resolve_deps
> [ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1127, in actually_resolve_deps
> [ResolutionFailure]:       resolver.resolve()
> [ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2022.3.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 905, in resolve
> [ResolutionFailure]:       raise ResolutionFailure(message=str(e))
> [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
>   You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
>   Hint: try $ pipenv lock --pre if it is a pre-release dependency.
> ERROR: No matching distribution found for nrel-pysam~=2.2
> ```
> 
> We would need to update `nrel-pysam`. Version 3.0.0 supports python 3.10 according to the [release notes](https://pypi.org/project/NREL-PySAM/). I will try and update the PR if it works.

It works. I have updated the **requirements.txt**, **Pipfile**, **setup.cfg** and the **.github/workflows/test.yml** files and regenerated the **Pifile.lock** file

**Review by jenhagg — APPROVED** [review]

**Pull request merged**
