### PR TITLE
Load zone file

### PR DESCRIPTION
**Pull request by rouille**
[Pull Request doc](https://breakthrough-energy.github.io/docs/user/git_guide.html#d-pull-request)

### Purpose
Add file enclosing information on load zone in a newly created data folder

### What the code is doing
N/A

### Testing
N/A

### Where to look
The file is located in **prereise/gather/griddata/hifld/data/**

### Usage Example/Visuals
N/A

### Time estimate
2min

### CODE REVIEW

**Comment by rouille** [comment]
Note that New Mexico *fully* belongs to the Western Interconnection.

**Comment by danielolsen** [comment]
> Note that New Mexico _fully_ belongs to the Western Interconnection.

This is not consistent with reality.

**Comment by BainanXia** [comment]
> Note that New Mexico _fully_ belongs to the Western Interconnection.

Based on the discussion [here](https://besciencescommunity.slack.com/archives/G01CC0B6139/p1626203626037900), a temporal solution for this is 
- We include another Eastern NM entry
- We add a clean up step for the output of this file excluding it to make it consistent with the current behavior.

**Comment by BainanXia** [comment]
I have another concern: we have same zone_names with different zone_ids in this mapping, however, in our current framework, they are used interchangeable. This might put us in trouble when this model is interacting with the rest of the modules, especially for the functions in PostREISE.

**Comment by danielolsen** [comment]
> I have another concern: we have same zone_names with different zone_ids in this mapping, however, in our current framework, they are used interchangeable. This might put us in trouble when this model is interacting with the rest of the modules, especially for the functions in PostREISE.

I think you are right, there are probably several places in the code that assume a 1-to-1 mapping of zone_id to zone_name and vice versa. Luckily this should be easy enough to fix, following the model of what's in PowerSimData now for the TAMU network: https://github.com/Breakthrough-Energy/PowerSimData/blob/021cb90279f5f57170d830673814a043b54e956f/powersimdata/network/usa_tamu/constants/zones.py

**Comment by rouille** [comment]
The new version of the file has 2 Montana, 2 New Mexico, 2 South Dakota and 4 Texas. The `zone_name` column is unique now.

**Review by danielolsen — APPROVED** [review]
Thanks

**Pull request merged**
